spring.application.name=shopping

# H2 Console Settings
# This enables the web-based database viewer
spring.h2.console.enabled=true
# Sets the URL path to access the console
spring.h2.console.path=/h2-console

# DataSource Configuration
# Tells Spring to use an in-memory H2 database named 'mydb'
spring.datasource.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
#spring.datasource.url=jdbc:h2:tcp://localhost/~/mydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password

# JPA / Hibernate Configuration
# Tells Hibernate to automatically create/update tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update
# Specifies the H2 SQL dialect for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

api.prefix=/api/v1